services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homelens-english-app
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - APP_ENV=development
    restart: unless-stopped
